### ISSUE TITLE
Version change on dipy doc does not work

### ISSUE THREAD

**Issue by pjsjongsung** [dipy/dipy.org#27]
If we try to change the version of the doc, anything lower than the current default 1.8.0 throws page not found. Selecting the dev version changes the link but does not change the number written on the bar (where we select the version, it still says 1.8.0)

**Comment by skoudoro** [comment]
Not sure what's going on here, it was working 1 month ago, I will look into it a bit later.

Thank you for pointing that

**Comment by skoudoro** [comment]
Fixed, closing
