### ISSUE TITLE
Dipy website image incorrect in example file.

### ISSUE THREAD

**Issue by Atharva-Shah-2298** [dipy/dipy.org#28]
The image in multi tensor simulation example is incorrect.

https://docs.dipy.org/stable/examples_built/simulations/simulate_multi_tensor.html#sphx-glr-examples-built-simulations-simulate-multi-tensor-py
![Screenshot 2024-02-16 at 2 41 54 PM](https://github.com/dipy/dipy.org/assets/118627741/86b2d88a-80c3-485b-a317-0ba8663dfa29)

**Comment by skoudoro** [comment]
fix on the last release, closing
