### ISSUE TITLE
Image organization in `_static/images` folder is improper

### ISSUE THREAD

**Issue by deka27** [dipy/dipy.org#50]
The images in `_static/images` folder that are being utilized for the blogs are improperly organized. I proposing a better way to organize images.

![image](https://github.com/user-attachments/assets/7174c0df-7bda-4ced-b58a-0977df0ec50e)

A better way would be to store the images in

```
_static/images/gsoc/[year]/[name_of_contributor]
```

I have utilized same format to store images in my [blogpost-migration PR](https://github.com/dipy/dipy.org/pull/49).

After moving the images, links for images in blogposts will also have to be updated.

**Comment by skoudoro** [comment]
closed by #51
