### ISSUE TITLE
Issue with Website Title

### ISSUE THREAD

**Issue by deka27** [dipy/dipy.org#54]
I am receiving this small issue with the Website Title. It says DIPY - Project name not set. I am not sure if its only me.

![image](https://github.com/user-attachments/assets/99bbce58-fa25-4034-a312-986970a32be2)

**Comment by skoudoro** [comment]
Is it when you build locally ? I can not reproduce when I go to Dipy.org

**Comment by deka27** [comment]
Even in my local the same issue occurs. Trying to see, if I can fix.

**Comment by deka27** [comment]
Added/Modified this line and got correct title.

![image](https://github.com/user-attachments/assets/5dc55d7f-d321-4b74-bf46-23e83fe6df36)


<img width="334" alt="image" src="https://github.com/user-attachments/assets/444b2002-e454-4e5a-a873-2920238e6cef">

**Comment by skoudoro** [comment]
Great can you create a small PR? Thanks!
